version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./psdata:/var/lib/postgresql/data
    networks:
      - carteira
volumes:
  psdata:
    driver: local

networks:
  carteira:
    driver: bridge